-- Script PostgreSQL/Neon para o projeto SNPro Estoque.
-- Execute no SQL Editor do Neon ou via psql.
-- Este script cria somente a estrutura do banco. Nao contem secrets.

BEGIN;

-- Para recriar um banco vazio do zero, descomente os DROP abaixo.
-- Cuidado: isso apaga dados existentes.
-- DROP TABLE IF EXISTS movimentacoes CASCADE;
-- DROP TABLE IF EXISTS importacoes_planilha CASCADE;
-- DROP TABLE IF EXISTS dashboard_graficos CASCADE;
-- DROP TABLE IF EXISTS produtos CASCADE;
-- DROP TABLE IF EXISTS locais CASCADE;
-- DROP TABLE IF EXISTS tipos_produto CASCADE;
-- DROP TABLE IF EXISTS equipamentos CASCADE;
-- DROP TABLE IF EXISTS usuarios CASCADE;

CREATE TABLE IF NOT EXISTS usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    email VARCHAR(150) NOT NULL,
    senha_hash VARCHAR(255) NOT NULL,
    perfil VARCHAR(30) NOT NULL DEFAULT 'Operador',
    status VARCHAR(30) NOT NULL DEFAULT 'Ativo',
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_usuarios_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS equipamentos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(80) NOT NULL,
    descricao TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'Ativo',
    CONSTRAINT uq_equipamentos_nome UNIQUE (nome)
);

CREATE TABLE IF NOT EXISTS tipos_produto (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(80) NOT NULL,
    descricao TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'Ativo',
    CONSTRAINT uq_tipos_produto_nome UNIQUE (nome)
);

CREATE TABLE IF NOT EXISTS locais (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    endereco VARCHAR(150),
    descricao TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'Ativo',
    CONSTRAINT uq_locais_nome UNIQUE (nome)
);

CREATE TABLE IF NOT EXISTS produtos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(50) NOT NULL,
    nome VARCHAR(150) NOT NULL,
    equipamento VARCHAR(80) NOT NULL,
    tipo_produto VARCHAR(80),
    local VARCHAR(100) NOT NULL,
    quantidade INTEGER NOT NULL DEFAULT 1,
    estoque_minimo INTEGER NOT NULL DEFAULT 1,
    ticket_medio NUMERIC(10, 2) NOT NULL DEFAULT 0.01,
    status VARCHAR(30) NOT NULL DEFAULT 'Ativo',
    descricao TEXT,
    CONSTRAINT uq_produtos_sku UNIQUE (sku),
    CONSTRAINT ck_produtos_status CHECK (status IN ('Ativo', 'Inativo', 'Testar', 'Funcionando', 'Descarte'))
);

CREATE TABLE IF NOT EXISTS movimentacoes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR(40) NOT NULL,
    produto_id INTEGER NOT NULL,
    produto_nome VARCHAR(150) NOT NULL,
    quantidade INTEGER NOT NULL DEFAULT 1,
    valor_unitario NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    total NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    local VARCHAR(100) NOT NULL,
    local_origem VARCHAR(100) NOT NULL,
    local_destino VARCHAR(100),
    observacao TEXT,
    criado_em TIMESTAMP NOT NULL,
    CONSTRAINT fk_movimentacoes_produto FOREIGN KEY (produto_id)
        REFERENCES produtos (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT ck_movimentacoes_tipo CHECK (tipo IN ('Entrada', 'Saida', 'Transferência')),
    CONSTRAINT ck_movimentacoes_transferencia_destino CHECK (
        (tipo = 'Transferência' AND local_destino IS NOT NULL AND btrim(local_destino) <> '')
        OR
        (tipo <> 'Transferência' AND local_destino IS NULL)
    )
);

CREATE TABLE IF NOT EXISTS importacoes_planilha (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_arquivo VARCHAR(200),
    produtos_skus TEXT NOT NULL DEFAULT '',
    total_novos INTEGER NOT NULL DEFAULT 0,
    total_atualizados INTEGER NOT NULL DEFAULT 0,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dashboard_graficos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(120) NOT NULL,
    fonte VARCHAR(40) NOT NULL DEFAULT 'produtos',
    tipo_grafico VARCHAR(20) NOT NULL DEFAULT 'barra',
    coluna_grupo VARCHAR(60) NOT NULL DEFAULT 'equipamento',
    metrica VARCHAR(60) NOT NULL DEFAULT 'contagem',
    filtro_coluna VARCHAR(60),
    filtro_operador VARCHAR(20),
    filtro_valor VARCHAR(120),
    criado_em TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_produtos_nome ON produtos (nome);
CREATE INDEX IF NOT EXISTS ix_produtos_equipamento ON produtos (equipamento);
CREATE INDEX IF NOT EXISTS ix_produtos_local ON produtos (local);
CREATE INDEX IF NOT EXISTS ix_movimentacoes_produto_id ON movimentacoes (produto_id);
CREATE INDEX IF NOT EXISTS ix_movimentacoes_local_origem ON movimentacoes (local_origem);
CREATE INDEX IF NOT EXISTS ix_movimentacoes_local_destino ON movimentacoes (local_destino);
CREATE INDEX IF NOT EXISTS ix_movimentacoes_criado_em ON movimentacoes (criado_em);

COMMIT;
